---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: static-disk
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "overlay",
    "type": "bridge",
    "bridge": "vm-bridge0",
    "isDefaultGateway": false,
    "isGateway": false,
    "ipam": {
      "type": "static",
      "addresses": [{"address": "10.77.77.3/24"}],
      "routes": [{ "dst": "10.77.0.0/16" }]
    }
  }'

---
apiVersion: virt.virtink.smartx.com/v1alpha1
kind: VirtualMachine
metadata:
  name: postgres14-disk
spec:
  # run policy could be Always, RerunOnFailure, Once, Manual,Halted
  runPolicy: Always
  instance:
    memory:
      size: 1Gi
    kernel:
      image: cicdteam/clh-kernel:5.15.12
      imagePullPolicy: IfNotPresent
      cmdline: "console=ttyS0 root=/dev/vda rw"
    disks:
      - name: disk
    interfaces:
      - name: pod
        masquerade:
          cidr: 10.0.2.0/30
      - name: overlay
        masquerade:
          cidr: 10.0.3.0/30
  networks:
    - name: pod
      pod: {}
    - name: overlay
      multus:
        networkName: static-disk
  volumes:
    - name: disk
      containerDisk:
        image: localhost:5001/pg14-disk-test:latest
        imagePullPolicy: Always
