name: vm-example

on:
  schedule:
    - cron:  '40 * * * *'
  workflow_dispatch: # adds ability to run this manually

env:
  VM_EXAMPLE_SOURCE: postgres:14-alpine
  VM_EXAMPLE_IMAGE:  neondatabase/vm-postgres:14-alpine

jobs:
  vm-example:
    runs-on: ubuntu-latest
    steps:

      - name: git checkout
        uses: actions/checkout@v3

      - name: install golang
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: build vm-builder
        run:  go build -o bin/vm-builder tools/vm-builder/main.go

      - name: docker - install qemu
        uses: docker/setup-qemu-action@v2
      - name: docker - setup buildx
        uses: docker/setup-buildx-action@v2
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.NEON_DOCKERHUB_USERNAME }}
          password: ${{ secrets.NEON_DOCKERHUB_PASSWORD }}

      - name: build and push vm-example image
        run: |
          bin/vm-builder -src ${{ env.VM_EXAMPLE_SOURCE }} -dst ${{ env.VM_EXAMPLE_IMAGE }}
          docker push -q ${{ env.VM_EXAMPLE_IMAGE }}
