---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: static-disk
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "overlay",
    "type": "bridge",
    "bridge": "vm-bridge0",
    "isDefaultGateway": false,
    "isGateway": false,
    "ipam": {
      "type": "static",
      "addresses": [{"address": "10.77.77.3/24"}],
      "routes": [{ "dst": "10.77.0.0/16" }]
    }
  }'

---
apiVersion: virt.virtink.smartx.com/v1alpha1
kind: VirtualMachine
metadata:
  name: postgres14-disk
spec:
  # run policy could be Always, RerunOnFailure, Once, Manual,Halted
  runPolicy: Always
  instance:
    # If we don't define socketsMax here, then virtink refuses to allow more than 1
    cpu:
      sockets: 1
      socketsMax: 8
      coresPerSocket: 1
    memory:
      size: 1Gi
    kernel:
      image: cicdteam/clh-kernel:5.15.12
      imagePullPolicy: IfNotPresent
      cmdline: "console=ttyS0 root=/dev/vda rw"
    disks:
      - name: disk
    interfaces:
      - name: pod
        masquerade:
          cidr: 10.0.2.0/30
      - name: overlay
        masquerade:
          cidr: 10.0.3.0/30
  sidecars:
    - name: autoscaler
      image: localhost:5001/autoscaler-sidecar:latest
      # VM's IP address is always 10.0.2.2 within the pod
      command: ["/usr/bin/autoscaler", "10.0.2.2"]
      lifecycle:
        preStop:
          exec: { "command": ["/bin/sh", "-c", "set -eu -o pipefail; kill $(cat autoscaler.pid)"]}
      volumeMounts:
        - name: "virtink"
          mountPath: "/var/run/virtink"
  networks:
    - name: pod
      pod: {}
    - name: overlay
      multus:
        networkName: static-disk
  volumes:
    - name: disk
      containerDisk:
        image: localhost:5001/pg14-disk-test:latest
        imagePullPolicy: Always
