apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: whereabouts-example
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "whereabouts-example",
    "type": "bridge",
    "bridge": "vm-bridge0",
    "isDefaultGateway": false,
    "isGateway": false,
    "ipMasq": false,
    "ipam": {
        "type": "whereabouts",
        "range": "10.77.77.0/24",
        "routes": [{"dst": "10.0.0.0/8"}]
      }
    }'

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    example: pod
  annotations:
    k8s.v1.cni.cncf.io/networks: whereabouts-example
spec:
  terminationGracePeriodSeconds: 2
  containers:
  - args:
    - ping
    - 8.8.8.8
    image: alpine:3.16
    imagePullPolicy: IfNotPresent
    name: alpine
    securityContext:
      privileged: true
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: example
              operator: Exists
          topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    example: pod
  annotations:
    k8s.v1.cni.cncf.io/networks: whereabouts-example
spec:
  terminationGracePeriodSeconds: 2
  containers:
  - args:
    - ping
    - 8.8.8.8
    image: alpine:3.16
    imagePullPolicy: IfNotPresent
    name: alpine
    securityContext:
      privileged: true
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: example
              operator: Exists
          topologyKey: kubernetes.io/hostname
